// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),

BUILDIN_DEF(isspawn,"i?"),
BUILDIN_DEF(fakeplayerzxc,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc1,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc2,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc3,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc4,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc5,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc6,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc7,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc8,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc9,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc10,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc11,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc12,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc13,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc14,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc15,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc16,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc17,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc18,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc19,"siisiiiiiiiiiii"),
BUILDIN_DEF(fakeplayerzxc20,"siisiiiiiiiiiii"),